---
title: "SaferActive Progress Report 1"
author: 
- Robin Lovelace
- Joey Talbot
date: "`r Sys.Date()`"
output: 
  memor::pdf_memo:
    use_profile: false
    logo: "uol-logo.png"
    short_title: short title
    watermark: Draft
    confidential: false
    libertine: false
    chinese: false
    logo_height: 1.2cm
    watermark_color: gray
    footer_on_first_page: true
    toc: false
    lot: false
    lof: false
    number_sections: true
    latex_engine: xelatex
---

```{r, eval=FALSE, echo=FALSE}
browseURL("reports/report1.pdf")
```


```{r setup}
library(knitr)
library(kableExtra)
library(ggplot2)
opts_chunk$set(warning = FALSE, message = FALSE)
```

# Section 1
Here is a table

```{r}
kable(mtcars[1:5, 1:5], booktabs = T, caption = "a table") %>%
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "left")
```

\clearpage 

# Section 2
Here is a plot.

```{r}
ggplot(mtcars, aes(x = mpg, y = wt)) +
  geom_point()
```


<!-- Reporting schedule: -->

<!-- 2020-06-01	3	Report 1: on input data and data	25.00% -->
<!-- 2020-09-01	6	Report 2: scenarios, workshop 1 and prototype web application to test	25.00% -->
<!-- 2020-12-01	9	Report 3: results and publication of open risk map data	25.00% -->
<!-- 2021-03-01	12	Final project report and end-of-project workshop	25.00% -->
<!-- 2021-06-01	15	Refined project web app pending feedback from workshop and stakeholders	 -->
