---
output: word_document
---

# Reframing active travel interventions as safety interventions: an exploration of the relationship between different interventions, uptake and casualty rates in the UK

Fear of unsafe roads and motor traffic are reported to be the main barriers to cycling in cities in the UK and internationally, implying that reducing road danger could be an effective strategy enabling cycling uptake.
Road safety interventions can be framed as active travel interventions.
On the other hand, an often-stated co-benefit of active travel interventions is that they will make the road safer, suggesting that at least some types of active travel interventions can be seen as road safety interventions.
Road safety and active travel can thus be seen as two sides of the same coin.

Given the urgency of the epidemic of 'road violence', which kills around 1.3 million people each year and is the leading cause of death among young people worldwide according to the World Health Organization, this paper posits that framing active travel interventions as public safety interventions may be advantageous from the perspective of vital public support for change.
Motivated by these premises, and recalling that road safety played a major role in political shifts favouring cycling the nation with highest mode share of cycling worldwide (The Netherlands), we analysed a range of pro-cycling interventions from road safety *and* cycling uptake perspectives.
Using data on cycling investment from government reports and open data from OpenStreetMap, we assess the extent to which new cycleways and other pro-cycling measures are associated with reduced crash rates according to the open access 'STATS19' dataset (2014-2019).
We hypothesise that new cycleways alone are not associated with safer roads for all modes, but that places with additional 'low traffic neighbourhood' type interventions such as 'filtered permeability' and reduced speed limits will see substantial reductions in crash rates for both pedestrians and cyclists.
Our findings provide a (still evolving) evidence base on which policy-relevant debates about the framing of active travel and road safety interventions can build.

